### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mehcode** [chaplinjs/chaplin#348]
- [ ] **Modules** [or **Component**] (#345).
  By _Module_ I mean a re-usable component that can be plugged in with something like:
  
  ``` coffee
  match 'account/', include('modules/account') 
  ```
  
  We need to set a standard for distribution of these. I'd recommend compiled, concatenated, etc. 
  much as Chaplin currently is. I'd further recommend we state that only pre-compilable 
  template languages be used (and that they be packaged as such). Also relevant CSS must 
  be included as well.
  
  Something like a re-usable auto-complete built on top of Backbone or a login 
  view that allowed for several kinds of login sources would be examples of this.
- [ ] **Extensions** (#345).
  I mean projects that extend the core functionality of Chaplin. 
  Something like `backbone.stickit` is an example of this (in functionality). 
- [ ] **Transitions between views** (#105).
  
  Not much to say on this now. But I am looking into it. Re-usable `Transition` objects
  referenced by views and bound to containers or regions is what is rolling around in my mind.
- [x] **Model from / to View bindings** (#138).
  For this https://github.com/NYTimes/backbone.stickit is pretty incredible. 
  A few things / improvements could be made (one of which is respecting inheritance when
  it comes to the bindings hash) but otherwise its been great integrating this into
  our big application.
- [ ] **Style pipeline** (#226).
  The more I think about it the more I like the idea of allowing a view to add and remove its 
  styles. I don't want tons of AJAX requests to get the CSS modules. A single built file 
  would be ideal. But as @molily stated when the issue was closed, this pays off in a 
  very big application. We are building a very big application and are looking into ways to 
  improve our architecture.
- [ ] **Optimizations**
  By this I just mean we need to add lots of benchmarks. And then work towards improving 
  those benchmarks. 

I'll add some more later. But does anyone have any comments or additional ideas. This post is mostly about a place for me to write down everything I'm in the process of (or wanting to be in the process of) working on.
